@startuml


| gws |
| gui | 
| db |
| gui |
: choose variable ;
: visualise locations\n(ADS and any quarks);
: identify new quark subset(s) by time;
| db | 
partition loop over quarks {
: identify atomic parent file ;
: identify quark fragments ;
: generate manifest ;
}
| gws |
: acquire manifest(s) ;
partition cf-move0 {
: estimate volume needed ;
}
if (volume) then (too much)
| gui |
: identify quarks to remove ;
| db |
: loop over quarks ;
| gws |
: acquire manifest(s) ;
partition cfmove-1 {
: remove data ; 
: update db ;
}
| db |
: update fragment locations ;
| gui |
: update variable locations ;
endif
| gws | 
partition cfmove-2 {
: acquire quarks ;
: update db;
}
| db |
: update fragment locations ;
| gui |
: update variable locations ;
end









@enduml