@startuml 
hide attributes
class core.Cell_Method #e8f4d6 {
    + id (BigAutoField)
    + method (CharField)
    + axis (CharField)
}


class core.Cell_MethodSet #e8f4d6 {
    + id (BigAutoField)
    + key (CharField)
    # methods (ManyToManyField)
}
core.Cell_MethodSet o--o core.Cell_Method


class core.CollectionType #e8f4d6 {
    - id (AutoField)
    + value (TextField)
    + key (CharField)
}


class core.Collection #e8f4d6 {
    + _proxied (JSONField)
    + name (CharField)
    + description (TextField)
    - id (AutoField)
    # type (ManyToManyField)
    # tags (ManyToManyField)
    # variables (ManyToManyField)
}
core.Collection o--o core.CollectionType
core.Collection o--o core.Tag
core.Collection o--o core.Variable


class core.Domain #e8f4d6 {
    - id (AutoField)
    + name (CharField)
    + region (CharField)
    + nominal_resolution (CharField)
    + size (PositiveIntegerField)
    + coordinates (CharField)
    + bbox_tl (FloatField)
    + bbox_tr (FloatField)
    + bbox_bl (FloatField)
    + bbox_br (FloatField)
}


class core.File #e8f4d6 {
    - id (AutoField)
    + name (CharField)
    + path (CharField)
    + size (PositiveIntegerField)
    + type (CharField)
    + checksum (CharField)
    + checksum_method (CharField)
    + uuid (UUIDField)
    + format (CharField)
    # locations (ManyToManyField)
}
core.File o--o core.Location
core.File .- core.File_type


class core.Location #e8f4d6 {
    - id (AutoField)
    + name (CharField)
    + volume (PositiveBigIntegerField)
}


class core.Manifest #e8f4d6 {
    - id (AutoField)
    ~ cfa_file (ForeignKey)
    + bounds (BinaryField)
    + units (CharField)
    + calendar (CharField)
    + total_size (PositiveBigIntegerField)
    + parent_uuid (UUIDField)
    # fragments (ManyToManyField)
}
core.Manifest <--* core.File
core.Manifest o--o core.File


class core.Relationship #e8f4d6 {
    + id (BigAutoField)
    + predicate (CharField)
    ~ subject (ForeignKey)
    ~ related_to (ForeignKey)
}
core.Relationship <--* core.Collection
core.Relationship <--* core.Collection


class core.Tag #e8f4d6 {
    - id (AutoField)
    + name (CharField)
}


class core.TimeDomain #e8f4d6 {
    + id (BigAutoField)
    + interval (PositiveIntegerField)
    + interval_units (CharField)
    + units (CharField)
    + calendar (CharField)
    + starting (FloatField)
    + ending (FloatField)
}


class core.VariableProperty #e8f4d6 {
    - id (AutoField)
    + key (CharField)
    + value (CharField)
}
core.VariableProperty .- core.VariableProperty_key


class core.Variable #e8f4d6 {
    - id (AutoField)
    + _proxied (JSONField)
    ~ spatial_domain (ForeignKey)
    ~ time_domain (ForeignKey)
    ~ cell_methods (ForeignKey)
    ~ in_file (ForeignKey)
    ~ in_manifest (ForeignKey)
    # key_properties (ManyToManyField)
}
core.Variable o--> core.Domain
core.Variable o--> core.TimeDomain
core.Variable o--> core.Cell_MethodSet
core.Variable <--* core.File
core.Variable o--> core.Manifest
core.Variable o--o core.VariableProperty


enum core.File_type{
    + C - ('C', 'CFA File')
    + A - ('A', 'CFA File holds atomic dataset(s)')
    + Q - ('Q', 'CFA File holds quark(s)')
    + S - ('S', 'Standalone File')
    + F - ('F', 'Fragment File')
}

enum core.VariableProperty_key{
    + SN - ('SN', 'standard_name')
    + LN - ('LN', 'long_name')
    + ID - ('ID', 'identity')
    + AO - ('AO', 'atomic_origin')
}

@enduml
