# Generated by Django 5.1.1 on 2024-09-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell_Method',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=1024)),
                ('axis', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('key', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('path', models.CharField(max_length=256)),
                ('checksum', models.CharField(max_length=1024)),
                ('checksum_method', models.CharField(max_length=256)),
                ('size', models.IntegerField()),
                ('format', models.CharField(default='Unknown format', max_length=256)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('_proxied', models.JSONField()),
                ('name', models.CharField(max_length=256, unique=True)),
                ('volume', models.IntegerField()),
                ('description', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.BooleanField()),
                ('properties', models.ManyToManyField(to='db.collectionproperty')),
                ('files', models.ManyToManyField(to='db.file')),
                ('tags', models.ManyToManyField(to='db.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('volume', models.IntegerField()),
                ('holds_files', models.ManyToManyField(to='db.file')),
                ('protocols', models.ManyToManyField(to='db.protocol')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='locations',
            field=models.ManyToManyField(related_name='filelocations', to='db.location'),
        ),
        migrations.AddField(
            model_name='file',
            name='replicas',
            field=models.ManyToManyField(to='db.location'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(max_length=50)),
                ('related_collection', models.ManyToManyField(related_name='related', to='db.collection')),
                ('subject_collection', models.ManyToManyField(related_name='subject', to='db.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Var_Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('json', models.BooleanField()),
                ('boolean_value', models.BooleanField()),
                ('char_value', models.TextField()),
                ('int_value', models.BigIntegerField()),
                ('real_value', models.FloatField()),
                ('key', models.CharField(max_length=128)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('_cell_methods', models.JSONField()),
                ('_proxied', models.JSONField()),
                ('cfdm_size', models.BigIntegerField()),
                ('long_name', models.CharField(max_length=1024, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cfdm_domain', models.CharField(max_length=1024)),
                ('standard_name', models.CharField(max_length=1024, null=True)),
                ('identity', models.CharField(max_length=1024)),
                ('in_collection', models.ManyToManyField(to='db.collection')),
                ('in_files', models.ManyToManyField(to='db.file')),
            ],
        ),
    ]
